[pytest]
testpaths = tests
pythonpath = src
python_files = test_*.py
python_functions = test_*
asyncio_mode = strict
addopts = -ra --strict-markers --strict-config

markers =
    asyncio: Run the test in an asyncio event loop.
