# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

REAL_SERVICE_CONNECTION_ENV_VARS = (
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTID",
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__CLIENTSECRET",
    "CONNECTIONS__SERVICE_CONNECTION__SETTINGS__TENANTID",
)